# Setup
title:               Wikilabs
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme .'
url:                 http://wikilabs.org
baseurl:             ''
paginate:            5
permalink: 			 /:slugified_categories/:title:output_ext

# About/contact
author:
  name:              alendo
  url:               https://twitter.com/alendo
  email:             alendo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0
google_analytics_id: #UA-XXXX-Y
