# Setup
title:               Wikilabs
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme .'
url:                 https://www.wikilabs.org
baseurl:             ''
paginate:            5
permalink: 			 /:year/:month/:day/:title:output_ext

# About/contact
author:
  name:              etcware
  url:               http://etcware.it
  email:             a.donnini@etcware.it

# Gems
plugins:
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-event-pages

# Custom vars
version:             0.1.0
google_analytics_id: #UA-XXXX-Y
